title: Kashif Mehdi | Data Science Portfolio

logo: "/images/Profile.png"

description: >

  I am a passionate data scientist with a knack for transforming raw data into valuable insights.
  Explore my portfolio to discover my projects, skills, and achievements. 

  <br><br>

  <a href="www.linkedin.com/in/kashifmehdi">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0

plugins:

- jekyll-remote-theme

google-analytics: UA-305168520-1
