title: Kashif Mehdi
logo: "/images/Profile.png"
description: >
  I am a recent graduate with a bachelor's degree in computer science, specializing in software engineering and data science. 
  I am proficient in programming languages such as Python and R, and have experience with machine learning algorithms and data analysis tools like TensorFlow and Pandas.I am eager to apply my knowledge and skills to solve real-world problems and contribute to a forward-thinking team. 

  <a href="www.linkedin.com/in/kashifmehdi">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google-analytics: UA-305168520-1
