
url: "https://kashifmehdi.github.io" # Replace with your GitHub username
logo: "/assets/images/Profile Pic.png" # Update the path to your logo image

# Navigation
nav_links:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Skills
    url: /skills/
  - title: Contact
    url: /contact/

# Social Links
social_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/kashifmehdi
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/kashifmehdi
    icon: fab fa-github

# Style
minimal_skin: dark
minimal_skin_flat: true
minimal_skin_icons: true

# Fonts
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Roboto Mono"
    weights: "400,400i,700,700i"

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Analytics
google_analytics: UA-305168520-1
