title: Kashif Mehdi
logo: "/images/Profile.png"
description: >
  I am a recent graduate with a bachelor's degree in computer science, specializing in software engineering and data science.

  <a href="www.linkedin.com/in/kashifmehdi">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google-analytics: UA-305168520-1
