# Site Settings
title: Kashif Mehdi | Data Science Portfolio
url: "https://your-github-username.github.io" # Replace with your GitHub username
logo: "/assets/images/logo.png" # Update the path to your logo image
description: >
  I am a passionate data scientist with a knack for transforming raw data into valuable insights.
  Explore my portfolio to discover my projects, skills, and achievements.

# Navigation
nav_links:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Skills
    url: /skills/
  - title: Contact
    url: /contact/

# Social Links
social_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/kashifmehdi
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/your-github-username
    icon: fab fa-github
  - title: Twitter
    url: https://twitter.com/your-twitter-handle
    icon: fab fa-twitter

# Style
minimal_skin: dark
minimal_skin_flat: true
minimal_skin_icons: true

# Fonts
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Roboto Mono"
    weights: "400,400i,700,700i"

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Analytics
google_analytics: UA-305168520-1
